In [5]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-5)


# 정규화 되지않은 input data = xy  Non-normalized inputs !!
# 아래 MinMaxScaler를 활용해서 정규화 시킨다
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

xy = MinMaxScaler(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
# 작은 값일때는 올라가지않고 끝남, 너무 큰 값은 발산한다.
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
# 1e-7 => 1e-5로 변경함.
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)



0 Cost:  0.193104 
Prediction:
 [[ 0.12289229]
 [ 0.35602394]
 [ 0.23409796]
 [ 0.07872088]
 [ 0.16524625]
 [ 0.10475062]
 [ 0.06896965]
 [ 0.01610442]]
1 Cost:  0.193091 
Prediction:
 [[ 0.12291386]
 [ 0.35604382]
 [ 0.23411459]
 [ 0.07873376]
 [ 0.16526157]
 [ 0.10476536]
 [ 0.06897905]
 [ 0.0161133 ]]
2 Cost:  0.193079 
Prediction:
 [[ 0.12293543]
 [ 0.35606372]
 [ 0.23413114]
 [ 0.0787466 ]
 [ 0.16527687]
 [ 0.10478012]
 [ 0.06898844]
 [ 0.01612221]]
3 Cost:  0.193066 
Prediction:
 [[ 0.12295701]
 [ 0.3560836 ]
 [ 0.23414773]
 [ 0.07875945]
 [ 0.16529217]
 [ 0.10479484]
 [ 0.06899784]
 [ 0.01613113]]
4 Cost:  0.193053 
Prediction:
 [[ 0.1229786 ]
 [ 0.35610351]
 [ 0.2341643 ]
 [ 0.07877234]
 [ 0.16530752]
 [ 0.10480955]
 [ 0.06900723]
 [ 0.01614001]]
5 Cost:  0.19304 
Prediction:
 [[ 0.12300017]
 [ 0.35612336]
 [ 0.23418087]
 [ 0.07878517]
 [ 0.16532281]
 [ 0.10482427]
 [ 0.06901661]
 [ 0.01614892]]
6 Cost:  0.193028 
Prediction:
 [[ 0.12302174]
 [ 0.35614324]
 [ 0.23419742]
 [ 0.0